Структуры для N, Z , методы их создания, функция модуля целого
Argentusz/DMTI_baza pull request #55
Opened 2022-03-24 21:43 UTC by Argentusz

2022-03-24 22:10 UTC, mishhgun01 commented
+ добавляй описание в PR, пж

2022-03-24 22:14 UTC, mishhgun01 requested changes

2022-03-24 22:14 UTC, mishhgun01 commented on whole/whole.go
> +	Older    uint32
сюда можно просто Natural, чтобы сохранялся принцип наследственности (в Go - принцип композиции, почитай, интересная штука)

2022-03-24 22:14 UTC, mishhgun01 commented on whole/whole.go
> +		if v != 0 { //Проверка на 0 старшей цифры
ну и соответственно не digits а Natural.digits (смотря как обзовёшь поле типа Naturals)

2022-03-24 22:16 UTC, GarlicRoll commented on natural/naturals.go
> +		if v != 0 { //Проверка на 0 старшей цифры
Нулевой элемент массива - старший разряд, было бы логичнее наоборот, но ладно
Судя по условию, если элемент не равен 0, то цикл прерывается и функция возвращает то, что успела записать. Может я чего-то не понимаю?

2022-03-24 22:16 UTC, GarlicRoll commented on whole/whole.go
> +type Whole struct {
целое переводится как whole, но, если мне не изменяет память, в другом значении, есть хорошее слово integer, оно вроде не ключевое

2022-03-24 22:16 UTC, GarlicRoll commented on whole/whole.go
> +	Negative bool // true (1), если отрицательное; false (0), если положительное
Я одобряю, не предвижу проблем из-за boolean вместо int

2022-03-24 22:16 UTC, GarlicRoll commented on whole/whole.go
> +		if v != 0 { //Проверка на 0 старшей цифры
(аналогичный вопрос в другом коммите)

2022-03-24 22:16 UTC, GarlicRoll commented on whole/whole.go
> +func Abs(w Whole) natural.Natural {
ABS_Z_N

2022-03-24 22:18 UTC, mishhgun01 commented on whole/whole.go
> +func Abs(w Whole) natural.Natural {
можно свои имена функциям давать, тут вполне уместно название Макса, а ABS_Z_N как то по нацистски выглядит..

2022-03-24 22:19 UTC, mishhgun01 commented on natural/naturals.go
> +		if v != 0 { //Проверка на 0 старшей цифры
все верно, мы идем с начала (со старшей цифры) и проверяем старшие разряды на 0. если не 0 в старшем разряде, уходим, в противном - режем слайс с 0ого элемента

2022-03-24 22:22 UTC, Argentusz commented on whole/whole.go
> +func Abs(w Whole) natural.Natural {
Не смогу заставить себя называть функции таким образом

2022-03-24 22:25 UTC, GarlicRoll commented on natural/naturals.go
> +		if v != 0 { //Проверка на 0 старшей цифры
Понял

2022-03-24 22:27 UTC, GarlicRoll commented on whole/whole.go
> +func Abs(w Whole) natural.Natural {
Я бы придерживался "нацисткой" терминологии, так удобнее в конечном счёте будет проверять Позднякову и вызывать функции нам, так как они записаны в таблице (тут пишет код не три человека)

2022-03-24 22:32 UTC, mishhgun01 commented on whole/whole.go
> +func Abs(w Whole) natural.Natural {
но он же сам сказал, что фугкции можем называть как удобно, он своей нейминг просто предлагает, а код хорошо комментирован, поэтому не должно возникнуть проблем с пониманием и читаемостью

2022-03-24 22:38 UTC, Argentusz commented on whole/whole.go
> +func Abs(w Whole) natural.Natural {
Ничего не мешает поменять в таблице у нас названия на нормальные. Сомневаюсь, что Сергей Николаевич знает эти названия наизусть и это доставит ему какое-либо неудобство

2022-03-25 08:12 UTC, Argentusz commented on whole/whole.go
> +type Whole struct {
Whole Number часто употребляют математики по отношению к Integer. Да и само слово integer - это буквально whole с лат.
Пусть будет так, да и мы путаться не будем

2022-03-25 08:37 UTC, icekomar approved these changes

2022-03-25 10:11 UTC, InterferenceCup approved these changes

2022-03-25 10:26 UTC, InterferenceCup approved these changes

2022-03-25 10:41 UTC, mishhgun01 approved these changes
ОК

2022-03-25 11:02 UTC, merged