функции перевода целое в дробное и обратно
Argentusz/DMTI_baza pull request #57
Opened 2022-03-27 18:51 UTC by Natanus2011

не бейте строго

2022-03-28 10:37 UTC, mishhgun01 requested changes

2022-03-28 10:37 UTC, mishhgun01 commented on rational/rational.go
> +	denominator natural.Natural
чтоб импортилось в другие пакеты лучше оставить заглавную..в го так работает

2022-03-28 10:37 UTC, mishhgun01 commented on rational/rational.go
> +	return &p
нужно возвращать не разыменованную ссылку, а копию
типа
```
func ...() Rational{
var p Rational
<code>
return p
}
```
+ нужно повысить читаемость - p:=Rational{} - неплохо, но читабельнее будет раскинуть на строки разные или сделать полноценно копию по типу var ratio Rational и обращаться по принципу инкапсуляции (то есть через точку - ratio.Nominator. итд)

2022-03-28 10:37 UTC, mishhgun01 commented on rational/rational.go
> +	p := whole.Whole{Negative: false, Num: x.nominator.Num}
и по неймингу - нужно придумать название (можно попробовать букввально через гугл переводчик
)

2022-03-28 10:38 UTC, mishhgun01 commented
В целом неплохо, но нужно повысить читаемость и избавиться от путаницы с указателями и ссылками - лучше создадим лишнюю копию в функции и вернём её - сборщик мусора уничтожит и потери в памяти несущественные

2022-03-28 18:54 UTC, mishhgun01 commented
и комментарии - над каждой функцией кратко от кого (фамилия) и что она делает

2022-04-02 10:34 UTC, mishhgun01 approved these changes
все выглядит хорошо

2022-04-02 11:12 UTC, InterferenceCup approved these changes

2022-04-02 18:53 UTC, merged