Turbina
Argentusz/DMTI_baza pull request #59
Opened 2022-03-30 05:44 UTC by hop-eee

Проверка на ноль: если число не равно нулю, то «да» иначе «нет»
Сравнение натуральных чисел: 2 - если первое больше второго, 0, если равно, 1 иначе.

2022-03-30 06:01 UTC, mishhgun01 requested changes
У меня только к ссылкам претензия, в остальном по логике и неймингу ок

2022-03-30 06:30 UTC, Argentusz reviewed
Хорошая работа
Ничего критичного, просто мои хотелки для читабильности

2022-03-30 06:30 UTC, Argentusz commented on natural/naturals.go
>  	var flag, res int
Если flag принимает только 0 и 1, то лучше делать
var flag bool
, но это, конечно, не критично, просто легче понимать

2022-03-30 06:30 UTC, Argentusz commented on natural/naturals.go
>  		res = 2
Лучше сразу делать return 2 / return 1 и т п, и места не занимает в памяти, и быстрее выполняется

2022-03-30 06:30 UTC, Argentusz commented on natural/naturals.go
> +	return res
Здесь тоже необязательно вводить переменную. res = true -> return true (завершает функцию), return res -> return false (если до этого места дошла программа, то должна вернуть false)

2022-04-02 09:14 UTC, InterferenceCup reviewed
Все отлично, все понятно, только лайк комменту про return'ы

2022-04-02 09:34 UTC, InterferenceCup approved these changes
👍

2022-04-02 09:38 UTC, Argentusz commented
К вечеру, думаю, мёрджим.

2022-04-02 09:40 UTC, Argentusz approved these changes

2022-04-02 09:41 UTC, icekomar approved these changes

2022-04-02 10:34 UTC, mishhgun01 approved these changes
согласен, мерджим

2022-04-02 18:53 UTC, merged