Semenov
Argentusz/DMTI_baza pull request #63
Opened 2022-04-04 11:52 UTC by cemkyc

Всем привет, написал функцию сложения двух натуральных чисел, проверьте, анон
Функция – Addiction

2022-04-05 19:19 UTC, Argentusz requested changes

2022-04-05 19:19 UTC, Argentusz commented on natural/naturals.go
> +				if a.Digits[0] >= 10 { //если именно последний разряд(самый левый) больше или равен 10
Не очень понял. Ты складываешь цифры и, если результат больше 10, проверяешь страший ли это разряд?
Если да то не очень понимаю что происходит далее. Если ты пытался сделать prepend (добавление в начала массива), то это можно сделать гораздо проще и понятнее (просто погугли prepend in golang)

2022-04-05 19:19 UTC, Argentusz commented on natural/naturals.go
> +		return *b
Лучше не возвращать ссылку на один из элементов передающихся в функцию, а просто копию

2022-04-05 19:19 UTC, Argentusz commented on natural/naturals.go
> +func Addiction(a, b *Natural) Natural {
Да и вообще лучше без звёздочки брать и делать копию. Не хочется, чтобы при передачи в функцию изменялись передаваемые параметры

2022-04-05 19:19 UTC, Argentusz commented on natural/naturals.go
>  		for i = 0; i <= a.Older; i++ {
Копировать одно и то же нежелательно. Можно ведь в начале программы проверить какое число больше и, возвращаясь к теме по копии, сделать две переменные: big и small, в которые сразу запишутся соответствующие числа. И код и чище станет, и безопаснее

2022-04-06 17:49 UTC, GarlicRoll requested changes
Лучше дейстивтельно делать копию
(Также Addition всё-таки)

2022-04-07 05:11 UTC, Argentusz requested changes

2022-04-07 05:11 UTC, Argentusz commented on natural/naturals.go
> +	u := &t
r t y u ? Ну, ладно, хоть не RGT_N_N TRE_NN_NQQ, но нейминг попнятнее нужен (на будущее)

2022-04-07 05:11 UTC, Argentusz commented on natural/naturals.go
> +	if Compare(y, u) != 2 || Compare(y, u) != 0 {
Compare != 2 ИЛИ Compare != 0 верно всегда!

2022-04-07 10:52 UTC, mishhgun01 commented on natural/naturals.go
> +	u := &t
можно же просто передавать по значению и CopyN не нужно будет использовать..
`func Addition(a, b Natural) Natural{
var res Natural
<code>
return res
}`

2022-04-07 12:58 UTC, Argentusz commented on natural/naturals.go
> +	u := &t
Нужно будет. Передача по "значению" структуры не копирует, а дает ссыль, как оказалось

2022-04-07 15:03 UTC, icekomar approved these changes

2022-04-07 15:18 UTC, hop-eee approved these changes

2022-04-07 15:45 UTC, mishhgun01 approved these changes

2022-04-07 16:08 UTC, Argentusz commented
Зарезолвил конфликт. Можно мёрджить

2022-04-07 16:09 UTC, merged