Сложение и Вычитание дробей
Argentusz/DMTI_baza pull request #84
Opened 2022-04-08 20:57 UTC by icekomar

Простите,простите,простите

2022-04-08 21:29 UTC, Argentusz requested changes
Не тот знак при вычитании из меньшего большего

2022-04-08 22:42 UTC, mishhgun01 requested changes
По логике у нас вроде Макс с Глебом в основном проверяют, я по кодстайлу и с тз языка посмотрел прежде всего

2022-04-08 22:42 UTC, mishhgun01 commented on rational/rational.go
> +		return res
можно(лучше) не помещать в else - блок, ведь у тебя уже есть return в if-случае, помещать основную логику в else - считается плохим тоном (Хахаев идиот, не слушайте его)

2022-04-08 22:42 UTC, mishhgun01 commented on rational/rational.go
> +	} else {
то же самое

2022-04-09 13:37 UTC, Argentusz reviewed
По логике вроде все ок

2022-04-09 13:37 UTC, Argentusz commented on rational/rational.go
> +		}
Уж подожди, когда Максюш пофиксит, а то лишний раз получается делаешь проверку

2022-04-09 17:45 UTC, closed without merging