Функция нахождения НОК и НОД
Argentusz/DMTI_baza pull request #96
Opened 2022-04-10 12:11 UTC by InterferenceCup

Не бейте за название и расписанный алгоритм пж пж

2022-04-10 14:51 UTC, Argentusz requested changes
Если один из коэффициентов 0, то вернёт ноль GCD. Стоит учесть

2022-04-10 15:01 UTC, InterferenceCup commented
> Если один из коэффициентов 0, то вернёт ноль GCD. Стоит учесть

Я думал это учитывается в функциях для натуральных чисел 0_о

2022-04-10 15:03 UTC, Argentusz commented
> Я думал это учитывается в функциях для натуральных чисел 0_о
Ну так если у тебя один из коэффов 0 то его нет и он вообще никак не должен учитываться

2022-04-10 15:05 UTC, InterferenceCup commented
> > Я думал это учитывается в функциях для натуральных чисел 0_о
> Ну так если у тебя один из коэффов 0 то его нет и он вообще никак не должен учитываться
> 
> 

Нет, я к тому, что, на ноль все делится без остатка, поэтому по сути функция нахождения НОД для натуральных должна при параметрах 0 и n выдавать n

2022-04-10 15:15 UTC, icekomar commented on polynome/polynomes.go
> +	}
а не проще сначала найти нод между 1 и 2 числителем к примеру и записать это в переменную , а потом просто идя по массиву, проверяя числители на 0, просто  искать нод между следующим числителем  и переменной

2022-04-10 15:15 UTC, icekomar commented on polynome/polynomes.go
> +	}
емае

2022-04-10 15:17 UTC, InterferenceCup commented on polynome/polynomes.go
> +	}
Не проще, проверок больше будет. Сейчас я переделаю копирование, чтоб оно не учитывало нули, это будет одна проверка и все. Если пробегать весь массив, искать и пропускать, проверок будет гораздо больше и код станет сложнее

2022-04-10 15:18 UTC, Argentusz commented on polynome/polynomes.go
> +	}
так круче
![E2272](https://user-images.githubusercontent.com/92330982/162626555-6554cbae-5e37-4448-a35e-84622860a35e.gif)
)

2022-04-10 15:18 UTC, icekomar commented on polynome/polynomes.go
> +	}
всмысле проверок будет больше

2022-04-10 15:20 UTC, icekomar commented on polynome/polynomes.go
> +	}
у тебя сейчас допустим для многочлена 3 степени, будет 6(если не ошибаюсь) поисков Нод, я де тебе предлагаю сократить для того же многочлена 3 степени до 3 поисков н

2022-04-10 15:21 UTC, icekomar commented on polynome/polynomes.go
> +	}
проверка на 0 будет столько раз, сколько 0 в числителях, с твоим циклом они тоже увеличатся

2022-04-10 15:23 UTC, icekomar commented on polynome/polynomes.go
> +	}
> так круче ![E2272](https://user-images.githubusercontent.com/92330982/162626555-6554cbae-5e37-4448-a35e-84622860a35e.gif) )
извиняюсь

2022-04-10 15:27 UTC, InterferenceCup commented on polynome/polynomes.go
> +	}
Во всяком случае ухудшится читабельность и так сложно функции. А Поздняков просил учитывать и это тоже. 
(Мне лень потом искать сто милЕардАв багов после написания этих проверок)

2022-04-10 19:09 UTC, Argentusz approved these changes

2022-04-10 19:30 UTC, icekomar approved these changes

2022-04-10 20:45 UTC, mishhgun01 approved these changes

2022-04-11 12:50 UTC, GarlicRoll commented on polynome/polynomes.go
> +	}
[https://vk.com/doc149088691_633526948]

2022-04-11 19:36 UTC, merged