Помогите
Argentusz/DMTI_baza pull request #99
Opened 2022-04-10 19:38 UTC by icekomar

Помогите найти Ошибку и протестите

2022-04-10 23:22 UTC, mishhgun01 requested changes

2022-04-10 23:22 UTC, mishhgun01 commented on polynome/polynomes.go
> +func MultiplicationPol(xOld, yOld Polynomial) Polynomial {
комментарий - от кого и для чего

2022-04-10 23:22 UTC, mishhgun01 commented on polynome/polynomes.go
> +func RemainderFromDivision(x1, x2 Polynomial) Polynomial {
same

2022-04-11 07:48 UTC, GarlicRoll approved these changes
Частное и остаток тесты проходят
Умножение - функция Наташи
Лучше комментировать переменные при инициализации или делать названия более понятными
Допиши комменты перед функциями!

2022-04-11 12:46 UTC, merged